### ISSUE TITLE
Включить GitHub Pages

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender_manual_ru#1]
Чтобы можно было читать html-ки прямо с GitHub-а. И чтоб поисковики нормально индексировали.
Инструкция: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/
Пример: https://facebook.github.io/react/

**Comment by PavelBlend** [comment]
https://pavelblend.github.io/blender_manual_ru/physics/fluid/index.html
